-- Music Video History Library / Database schema v1
-- Target: Supabase / PostgreSQL

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.work_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.works (
  id uuid primary key default gen_random_uuid(),
  work_type_id bigint not null references public.work_types(id),
  slug text not null unique,
  title text not null,
  original_title text,
  release_date date,
  release_year smallint check (release_year is null or release_year between 1890 and 2200),
  country_code text,
  language_code text,
  status text not null default 'draft' check (status in ('draft','candidate','researching','verified','published','archived','rejected')),
  is_canonical boolean not null default false,
  historical_importance smallint check (historical_importance between 1 and 5),
  visual_innovation smallint check (visual_innovation between 1 and 5),
  cultural_impact smallint check (cultural_impact between 1 and 5),
  craft_excellence smallint check (craft_excellence between 1 and 5),
  reference_value smallint check (reference_value between 1 and 5),
  short_summary text,
  why_it_matters text,
  historical_context text,
  key_innovation text,
  editorial_notes text,
  last_reviewed_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (release_date is null or release_year is null or extract(year from release_date)::smallint = release_year)
);

create index if not exists works_status_idx on public.works(status);
create index if not exists works_release_year_idx on public.works(release_year);
create index if not exists works_work_type_idx on public.works(work_type_id);

create trigger works_set_updated_at
before update on public.works
for each row execute function public.set_updated_at();

create table if not exists public.music_video_details (
  work_id uuid primary key references public.works(id) on delete cascade,
  label text,
  album text,
  runtime_seconds integer check (runtime_seconds is null or runtime_seconds > 0),
  official_release_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger music_video_details_set_updated_at
before update on public.music_video_details
for each row execute function public.set_updated_at();

create table if not exists public.entities (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  display_name text not null,
  original_name text,
  entity_type text not null check (entity_type in ('person','artist_group','band','company','agency','studio','collective','brand','institution','other')),
  country_code text,
  biography text,
  official_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists entities_display_name_idx on public.entities(display_name);
create index if not exists entities_type_idx on public.entities(entity_type);

create trigger entities_set_updated_at
before update on public.entities
for each row execute function public.set_updated_at();

create table if not exists public.credit_roles (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  role_group text not null,
  sort_order integer not null default 100,
  description text
);

create table if not exists public.work_credits (
  id uuid primary key default gen_random_uuid(),
  work_id uuid not null references public.works(id) on delete cascade,
  entity_id uuid not null references public.entities(id),
  role_id bigint not null references public.credit_roles(id),
  credited_as text,
  credit_order integer not null default 1,
  notes text,
  verification_status text not null default 'unverified' check (verification_status in ('unverified','source_found','verified','disputed')),
  created_at timestamptz not null default now(),
  unique (work_id, entity_id, role_id)
);

create index if not exists work_credits_work_idx on public.work_credits(work_id);
create index if not exists work_credits_entity_idx on public.work_credits(entity_id);
create index if not exists work_credits_role_idx on public.work_credits(role_id);

create table if not exists public.taxonomy_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  allows_multiple boolean not null default true
);

create table if not exists public.taxonomy_terms (
  id uuid primary key default gen_random_uuid(),
  category_id bigint not null references public.taxonomy_categories(id),
  slug text not null,
  name text not null,
  description text,
  parent_term_id uuid references public.taxonomy_terms(id),
  created_at timestamptz not null default now(),
  unique (category_id, slug)
);

create table if not exists public.work_taxonomy_terms (
  work_id uuid not null references public.works(id) on delete cascade,
  term_id uuid not null references public.taxonomy_terms(id),
  confidence numeric(4,3) check (confidence is null or confidence between 0 and 1),
  assignment_method text not null default 'editorial' check (assignment_method in ('editorial','community','automated','imported')),
  notes text,
  created_at timestamptz not null default now(),
  primary key (work_id, term_id)
);

create table if not exists public.awards (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  country_code text,
  official_url text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.award_categories (
  id uuid primary key default gen_random_uuid(),
  award_id uuid not null references public.awards(id) on delete cascade,
  slug text not null,
  name text not null,
  description text,
  unique (award_id, slug)
);

create table if not exists public.work_award_results (
  id uuid primary key default gen_random_uuid(),
  work_id uuid not null references public.works(id) on delete cascade,
  award_category_id uuid not null references public.award_categories(id),
  award_year smallint not null check (award_year between 1900 and 2200),
  result text not null check (result in ('winner','nominee','shortlist','official_selection','honorable_mention')),
  notes text,
  verification_status text not null default 'unverified' check (verification_status in ('unverified','source_found','verified','disputed')),
  unique (work_id, award_category_id, award_year)
);

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  work_id uuid not null references public.works(id) on delete cascade,
  platform text not null,
  asset_type text not null check (asset_type in ('full_video','trailer','teaser','making_of','case_study','thumbnail','stills','article','other')),
  external_id text,
  url text not null,
  is_official boolean not null default false,
  availability_status text not null default 'unknown' check (availability_status in ('available','unlisted','removed','region_locked','archived','metadata_only','unknown')),
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  unique (work_id, url)
);

create unique index if not exists media_assets_platform_external_id_unique
on public.media_assets(platform, external_id)
where external_id is not null;

create table if not exists public.sources (
  id uuid primary key default gen_random_uuid(),
  source_type text not null check (source_type in ('official_video','artist_official','director_portfolio','production_company','vfx_company','award_archive','label','publication','database','other')),
  title text,
  publisher text,
  url text not null unique,
  accessed_at date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.work_sources (
  work_id uuid not null references public.works(id) on delete cascade,
  source_id uuid not null references public.sources(id) on delete cascade,
  supports_fields text[] not null default '{}',
  is_primary boolean not null default false,
  notes text,
  primary key (work_id, source_id)
);

create table if not exists public.curricula (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text,
  level text check (level in ('beginner','intermediate','advanced','professional')),
  status text not null default 'draft' check (status in ('draft','published','archived')),
  estimated_days integer check (estimated_days is null or estimated_days > 0),
  items_per_day integer check (items_per_day is null or items_per_day > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger curricula_set_updated_at
before update on public.curricula
for each row execute function public.set_updated_at();

create table if not exists public.curriculum_items (
  curriculum_id uuid not null references public.curricula(id) on delete cascade,
  work_id uuid not null references public.works(id) on delete cascade,
  sequence_number integer not null check (sequence_number > 0),
  day_number integer check (day_number is null or day_number > 0),
  lesson_title text,
  lesson_note text,
  primary key (curriculum_id, work_id),
  unique (curriculum_id, sequence_number)
);

create table if not exists public.work_relationships (
  source_work_id uuid not null references public.works(id) on delete cascade,
  target_work_id uuid not null references public.works(id) on delete cascade,
  relationship_type text not null check (relationship_type in ('influenced_by','influenced','similar_visual_language','same_campaign','remake','homage','response','other')),
  notes text,
  verification_status text not null default 'unverified' check (verification_status in ('unverified','source_found','verified','disputed')),
  primary key (source_work_id, target_work_id, relationship_type),
  check (source_work_id <> target_work_id)
);

insert into public.work_types (code, name, description)
values
  ('music_video','Music Video','Official or artist-sanctioned music video'),
  ('commercial','Commercial','Advertising film or campaign work'),
  ('film','Film','Feature or short film'),
  ('title_sequence','Title Sequence','Opening or closing title sequence'),
  ('fashion_film','Fashion Film','Fashion-focused moving image work')
on conflict (code) do nothing;

insert into public.credit_roles (code, name, role_group, sort_order)
values
  ('artist','Artist','music',10),
  ('featured_artist','Featured Artist','music',20),
  ('director','Director','direction',30),
  ('co_director','Co-Director','direction',31),
  ('production_company','Production Company','production',40),
  ('service_production','Service Production','production',41),
  ('agency','Agency','production',42),
  ('executive_producer','Executive Producer','production',50),
  ('producer','Producer','production',51),
  ('director_of_photography','Director of Photography','camera',60),
  ('production_designer','Production Designer','art',70),
  ('editor','Editor','post',80),
  ('vfx_production','VFX Production','vfx',90),
  ('vfx_supervisor','VFX Supervisor','vfx',91),
  ('colorist','Colorist','post',100),
  ('choreographer','Choreographer','performance',110),
  ('animation_studio','Animation Studio','animation',120)
on conflict (code) do nothing;

insert into public.taxonomy_categories (code, name, description)
values
  ('genre','Music Genre','Broad music genre'),
  ('technique','Technique','Production or image-making technique'),
  ('camera','Camera','Camera movement, lens, rig, and capture method'),
  ('lighting','Lighting','Lighting style and approach'),
  ('color','Color','Palette and color treatment'),
  ('editing','Editing','Editing rhythm, transition, and structure'),
  ('visual_style','Visual Style','Visual language and aesthetic'),
  ('narrative','Narrative','Narrative structure and storytelling mode'),
  ('performance','Performance','Dance, acting, lip-sync, and performance mode'),
  ('location','Location','Location and spatial setting'),
  ('technology','Technology','Notable technologies used'),
  ('mood','Mood','Emotional and atmospheric quality'),
  ('format','Format','Capture or presentation format'),
  ('curriculum_topic','Curriculum Topic','Educational grouping')
on conflict (code) do nothing;

-- RLS
alter table public.work_types enable row level security;
alter table public.works enable row level security;
alter table public.music_video_details enable row level security;
alter table public.entities enable row level security;
alter table public.credit_roles enable row level security;
alter table public.work_credits enable row level security;
alter table public.taxonomy_categories enable row level security;
alter table public.taxonomy_terms enable row level security;
alter table public.work_taxonomy_terms enable row level security;
alter table public.awards enable row level security;
alter table public.award_categories enable row level security;
alter table public.work_award_results enable row level security;
alter table public.media_assets enable row level security;
alter table public.sources enable row level security;
alter table public.work_sources enable row level security;
alter table public.curricula enable row level security;
alter table public.curriculum_items enable row level security;
alter table public.work_relationships enable row level security;

create policy "Public can read work types" on public.work_types for select to anon, authenticated using (true);
create policy "Public can read credit roles" on public.credit_roles for select to anon, authenticated using (true);
create policy "Public can read taxonomy categories" on public.taxonomy_categories for select to anon, authenticated using (true);
create policy "Public can read taxonomy terms" on public.taxonomy_terms for select to anon, authenticated using (true);
create policy "Public can read published works" on public.works for select to anon, authenticated using (status = 'published');

create policy "Public can read published music video details"
on public.music_video_details for select to anon, authenticated
using (exists (select 1 from public.works w where w.id = music_video_details.work_id and w.status = 'published'));

create policy "Public can read credited entities"
on public.entities for select to anon, authenticated
using (exists (
  select 1 from public.work_credits wc
  join public.works w on w.id = wc.work_id
  where wc.entity_id = entities.id and w.status = 'published'
));

create policy "Public can read published work credits"
on public.work_credits for select to anon, authenticated
using (exists (select 1 from public.works w where w.id = work_credits.work_id and w.status = 'published'));

create policy "Public can read published work taxonomy"
on public.work_taxonomy_terms for select to anon, authenticated
using (exists (select 1 from public.works w where w.id = work_taxonomy_terms.work_id and w.status = 'published'));

create policy "Public can read awards" on public.awards for select to anon, authenticated using (true);
create policy "Public can read award categories" on public.award_categories for select to anon, authenticated using (true);

create policy "Public can read published award results"
on public.work_award_results for select to anon, authenticated
using (exists (select 1 from public.works w where w.id = work_award_results.work_id and w.status = 'published'));

create policy "Public can read published media assets"
on public.media_assets for select to anon, authenticated
using (exists (select 1 from public.works w where w.id = media_assets.work_id and w.status = 'published'));

create policy "Public can read published curricula"
on public.curricula for select to anon, authenticated
using (status = 'published');

create policy "Public can read published curriculum items"
on public.curriculum_items for select to anon, authenticated
using (
  exists (select 1 from public.curricula c where c.id = curriculum_items.curriculum_id and c.status = 'published')
  and exists (select 1 from public.works w where w.id = curriculum_items.work_id and w.status = 'published')
);

create policy "Public can read published work relationships"
on public.work_relationships for select to anon, authenticated
using (
  exists (select 1 from public.works w where w.id = work_relationships.source_work_id and w.status = 'published')
  and exists (select 1 from public.works w where w.id = work_relationships.target_work_id and w.status = 'published')
);

commit;
