-- MVHL Knowledge Graph Sprint 1
-- Controlled bilingual master data. These are concept definitions only; no
-- work relationships are inferred by this migration.

begin;

insert into public.technologies (
  slug, name, name_ja, description, description_ja, technology_type,
  aliases, definition_source_url, lifecycle_status, is_active
)
values
  ('rotoscoping', 'Rotoscoping', 'ロトスコープ',
   'A frame-by-frame process that traces recorded movement to create animation or isolate image elements.',
   '撮影した動きをフレームごとにトレースし、アニメーションの作成や映像要素の切り分けに用いる技術。',
   'animation', array['rotoscope'], 'https://www.adobe.com/creativecloud/video/discover/rotoscoping-animation.html', 'published', true),
  ('motion-control', 'Motion Control', 'モーションコントロール',
   'A camera system that records and precisely repeats programmed movement for synchronized passes and compositing.',
   'プログラムしたカメラ移動を記録・高精度に反復し、同期した複数パスの撮影や合成を可能にするシステム。',
   'camera', array['motion control camera'], 'https://www.mrmoco.com/', 'published', true),
  ('steadicam', 'Steadicam', 'ステディカム',
   'A body-supported camera stabilizing system that enables fluid movement while reducing shake from the operator.',
   'オペレーターの身体で支持し、歩行などの揺れを抑えながら流動的なカメラ移動を可能にする安定化システム。',
   'camera', array['camera stabilizer'], 'https://tiffen.com/pages/steadicam', 'published', true),
  ('cgi', 'CGI', 'CGI',
   'Computer-generated imagery created or substantially constructed through digital three-dimensional or two-dimensional processes.',
   'デジタルの3Dまたは2D工程によって生成、あるいは大幅に構築されたコンピューター生成映像。',
   'vfx', array['computer-generated imagery'], 'https://www.autodesk.com/media-and-entertainment/visual-effects', 'published', true),
  ('digital-compositing', 'Digital Compositing', 'デジタルコンポジット',
   'The digital combination of separately captured or generated image layers into a single finished shot.',
   '別々に撮影・生成した複数の映像レイヤーを、デジタル処理で一つの完成ショットに統合する技術。',
   'post_production', array['compositing'], 'https://www.adobe.com/products/aftereffects/compositing.html', 'published', true),
  ('morphing', 'Morphing', 'モーフィング',
   'A digital transformation that interpolates shape and image features between one subject or state and another.',
   '形状や画像特徴を補間し、一つの対象・状態から別の対象・状態へ連続的に変形させるデジタル技術。',
   'vfx', array[]::text[], null, 'published', true),
  ('stop-motion-photography', 'Stop-Motion Photography', 'ストップモーション撮影',
   'A frame-by-frame capture process in which physical subjects are incrementally moved between exposures.',
   '物理的な被写体を少しずつ動かしながら一コマずつ撮影し、連続運動として見せる撮影技術。',
   'animation', array['stop motion photography'], 'https://www.adobe.com/creativecloud/video/discover/stop-motion-animation.html', 'published', true),
  ('high-speed-photography', 'High-Speed Photography', 'ハイスピード撮影',
   'Image capture at a high frame rate so rapid action can be observed in slow motion during playback.',
   '高いフレームレートで撮影し、高速な現象を再生時にスローモーションとして観察できるようにする技術。',
   'capture', array['high speed camera'], 'https://www.phantomhighspeed.com/', 'published', true),
  ('time-lapse-photography', 'Time-Lapse Photography', 'タイムラプス撮影',
   'Image capture at spaced intervals that compresses long-duration change into a shorter moving sequence.',
   '一定間隔で撮影した画像を連続再生し、長時間の変化を短い映像へ圧縮する撮影技術。',
   'capture', array['timelapse'], null, 'published', true),
  ('motion-capture', 'Motion Capture', 'モーションキャプチャ',
   'A system that records the movement of a performer or object as data for driving a digital representation.',
   '人物や物体の動きをデータとして記録し、デジタル上の表現を駆動するためのシステム。',
   'capture', array['mocap'], 'https://www.vicon.com/about-us/what-is-motion-capture/', 'published', true),
  ('performance-capture', 'Performance Capture', 'パフォーマンスキャプチャ',
   'An expanded motion-capture process that records expressive performance such as body, face and sometimes voice together.',
   '身体、表情、場合によっては音声を含む俳優の表現を統合的に記録する拡張型モーションキャプチャ技術。',
   'capture', array['facial capture'], 'https://www.vicon.com/about-us/what-is-motion-capture/', 'published', true),
  ('3d-camera-tracking', '3D Camera Tracking', '3Dカメラトラッキング',
   'A process that reconstructs a camera movement in three-dimensional space from recorded footage.',
   '撮影映像を解析し、三次元空間におけるカメラの位置と動きを再構築する技術。',
   'post_production', array['camera solve', 'matchmove'], 'https://helpx.adobe.com/after-effects/using/tracking-3d-camera-movement.html', 'published', true),
  ('projection-mapping', 'Projection Mapping', 'プロジェクションマッピング',
   'Projection aligned to the geometry of a surface or object so imagery appears spatially integrated with it.',
   '面や物体の形状に合わせて投影を調整し、映像を空間や造形と一体化して見せる技術。',
   'display', array['spatial augmented reality'], null, 'published', true),
  ('drone-cinematography', 'Drone Cinematography', 'ドローン撮影',
   'Aerial image capture using a remotely operated or automated unmanned aircraft carrying a camera.',
   'カメラを搭載した無人航空機を遠隔操作または自動制御し、空中から映像を撮影する技術。',
   'camera', array['aerial drone'], 'https://www.dji.com/', 'published', true),
  ('fpv-drone', 'FPV Drone', 'FPVドローン',
   'Drone cinematography piloted through a live first-person video feed, often enabling fast and confined flight paths.',
   '機体からの一人称ライブ映像を見ながら操縦し、高速移動や狭い空間の飛行経路を可能にするドローン撮影。',
   'camera', array['first-person-view drone'], 'https://www.dji.com/avata-2', 'published', true),
  ('robotic-camera', 'Robotic Camera', 'ロボティックカメラ',
   'A camera mounted on a programmable robotic system for precise, repeatable or high-speed movement.',
   'プログラム可能なロボット機構にカメラを搭載し、高精度・反復可能・高速な動きを実現するシステム。',
   'camera', array['robot arm camera'], 'https://www.mrmoco.com/', 'published', true),
  ('led-volume', 'LED Volume', 'LEDボリューム',
   'A stage surrounded by large LED displays that presents real-time or pre-rendered environments during photography.',
   '大型LEDディスプレイで撮影空間を囲み、リアルタイムまたは事前生成した背景を撮影時に表示するステージ技術。',
   'display', array['led wall', 'volume stage'], 'https://www.unrealengine.com/en-US/explainers/virtual-production/what-is-an-led-volume', 'published', true),
  ('virtual-production', 'Virtual Production', 'バーチャルプロダクション',
   'Production workflows that integrate physical photography with real-time digital environments and visualization.',
   '実写撮影とリアルタイムのデジタル環境・可視化を統合して制作するワークフロー。',
   'production', array[]::text[], 'https://www.unrealengine.com/en-US/explainers/virtual-production/what-is-virtual-production', 'published', true),
  ('real-time-rendering', 'Real-Time Rendering', 'リアルタイムレンダリング',
   'Image generation fast enough to respond interactively to changes in camera, lighting, geometry or performance.',
   'カメラ、照明、形状、演技などの変化に対し、対話的に応答できる速度で画像を生成する技術。',
   'vfx', array[]::text[], 'https://www.unrealengine.com/en-US/explainers/real-time-rendering/what-is-real-time-rendering', 'published', true),
  ('unreal-engine', 'Unreal Engine', 'Unreal Engine',
   'A real-time three-dimensional creation platform used for interactive rendering, previs and virtual production.',
   'インタラクティブレンダリング、プリビズ、バーチャルプロダクションに用いられるリアルタイム3D制作基盤。',
   'production', array['ue'], 'https://www.unrealengine.com/', 'published', true),
  ('volumetric-capture', 'Volumetric Capture', 'ボリュメトリックキャプチャ',
   'A multi-view recording process that reconstructs a performer or scene as viewable three-dimensional data over time.',
   '複数視点からの記録をもとに、人物や空間を時間変化を伴う三次元データとして再構築する技術。',
   'capture', array['volumetric video'], null, 'published', true),
  ('volumetric-scan', 'Volumetric Scan', 'ボリュメトリックスキャン',
   'A spatial scanning process that records the three-dimensional form or occupancy of a subject or environment.',
   '被写体や環境の三次元形状・占有情報を空間データとして記録するスキャン技術。',
   'capture', array['volumetric scanning', '3d scan'], null, 'published', true),
  ('point-cloud-capture', 'Point Cloud Capture', '点群キャプチャ',
   'A capture process that represents surfaces or space as a set of measured three-dimensional points.',
   '表面や空間を、計測された三次元座標点の集合として記録する技術。',
   'capture', array['point cloud scanning'], 'https://www.autodesk.com/solutions/point-cloud', 'published', true),
  ('lidar', 'LiDAR', 'LiDAR',
   'Active distance measurement using laser pulses to generate spatial coordinates and often dense point clouds.',
   'レーザーパルスによる能動的な距離計測から空間座標を取得し、主に高密度な点群を生成する技術。',
   'capture', array['laser scanning'], 'https://www.usgs.gov/faqs/what-lidar-data-and-where-can-i-download-it', 'published', true),
  ('photogrammetry', 'Photogrammetry', 'フォトグラメトリ',
   'The reconstruction of measurements, geometry or surface information from overlapping photographs.',
   '重複して撮影した複数の写真から、寸法・形状・表面情報を再構築する技術。',
   'capture', array[]::text[], 'https://www.autodesk.com/solutions/photogrammetry-software', 'published', true),
  ('gaussian-splatting', 'Gaussian Splatting', 'ガウシアンスプラッティング',
   'A scene-representation and rendering method that uses optimized three-dimensional Gaussian primitives for novel-view synthesis.',
   '最適化した三次元ガウスプリミティブで空間を表現し、新規視点の画像を生成するレンダリング手法。',
   'vfx', array['3d gaussian splatting'], 'https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/', 'published', true),
  ('procedural-animation', 'Procedural Animation', 'プロシージャルアニメーション',
   'Animation generated or controlled through rules, simulations, parameters or algorithms rather than only hand-authored keyframes.',
   '手作業のキーフレームだけでなく、規則・シミュレーション・パラメータ・アルゴリズムで生成または制御するアニメーション。',
   'animation', array[]::text[], 'https://www.sidefx.com/products/houdini/', 'published', true),
  ('particle-simulation', 'Particle Simulation', 'パーティクルシミュレーション',
   'A simulation that models many discrete elements to create effects such as dust, sparks, fluids or abstract motion.',
   '多数の離散要素を計算し、塵、火花、流体、抽象的な運動などを表現するシミュレーション技術。',
   'vfx', array['particle system'], 'https://www.sidefx.com/products/houdini/', 'published', true),
  ('generative-graphics', 'Generative Graphics', 'ジェネラティブグラフィックス',
   'Visual imagery produced through a rule-based or algorithmic system that can generate variation over time.',
   '規則やアルゴリズムに基づくシステムによって生成され、時間的な変化や複数のバリエーションを持つ映像表現。',
   'vfx', array['generative art'], 'https://processing.org/', 'published', true),
  ('ai-image-generation', 'AI Image Generation', 'AI画像生成',
   'The generation or transformation of still imagery using a machine-learning model trained on image data.',
   '画像データで学習した機械学習モデルを用いて、静止画像を生成または変換する技術。',
   'vfx', array['text-to-image'], null, 'published', true),
  ('ai-video-generation', 'AI Video Generation', 'AI動画生成',
   'The generation or transformation of moving imagery using a machine-learning model that models temporal visual information.',
   '時間的な映像情報を扱う機械学習モデルを用いて、動画を生成または変換する技術。',
   'vfx', array['text-to-video'], 'https://openai.com/index/sora/', 'published', true)
on conflict (slug) do update set
  name = excluded.name,
  name_ja = excluded.name_ja,
  description = excluded.description,
  description_ja = excluded.description_ja,
  technology_type = excluded.technology_type,
  aliases = excluded.aliases,
  definition_source_url = excluded.definition_source_url,
  lifecycle_status = excluded.lifecycle_status,
  is_active = excluded.is_active;

insert into public.visual_languages (
  slug, name, name_ja, description, description_ja, visual_language_type,
  aliases, definition_source_url, lifecycle_status, is_active
)
values
  ('one-take', 'One Take', 'ワンテイク',
   'A work or sequence recorded as one genuinely uninterrupted camera take.',
   '実際に中断のない一回の撮影で構成された作品またはシークエンス。',
   'camera_language', array['single take'], null, 'published', true),
  ('continuous-shot-illusion', 'Continuous Shot Illusion', '連続ショット錯視',
   'Hidden cuts, transitions or compositing create the appearance of a single continuous take.',
   '隠しカット、トランジション、合成によって、一続きのワンテイクに見せる映像構成。',
   'editing', array['fake one take'], null, 'published', true),
  ('loop', 'Loop', 'ループ',
   'A repeated visual action, sequence or structure used as a recurring unit rather than a seamless endpoint.',
   '視覚的な動作・シークエンス・構造を、反復する単位として用いる表現。',
   'editing', array['repetition'], null, 'published', true),
  ('infinite-loop', 'Infinite Loop', '無限ループ',
   'A loop whose ending is designed to return seamlessly or conceptually to its beginning.',
   '終点が始点へ連続的または概念的に戻り、終わりのない循環として見えるループ表現。',
   'editing', array['seamless loop'], null, 'published', true),
  ('match-cut', 'Match Cut', 'マッチカット',
   'A cut that links shots through matching shape, movement, composition, sound or meaning.',
   '形、動き、構図、音、意味などの対応関係によって異なるショットを接続する編集表現。',
   'editing', array[]::text[], null, 'published', true),
  ('rhythmic-editing', 'Rhythmic Editing', 'リズミック編集',
   'Editing whose shot duration, transitions or internal movement are organized in a pronounced rhythmic pattern.',
   'ショット長、切り替え、画面内運動を明確なリズムに沿って構成する編集表現。',
   'editing', array['rhythm editing'], null, 'published', true),
  ('reverse-narrative', 'Reverse Narrative', '逆行ナラティブ',
   'A narrative structure that presents events in reverse chronological or causal order.',
   '出来事を時間または因果の逆順で提示する物語構造。',
   'narrative', array['reverse chronology'], null, 'published', true),
  ('split-screen', 'Split Screen', 'スプリットスクリーン',
   'Two or more distinct images are displayed simultaneously within divided regions of the frame.',
   '画面を分割し、二つ以上の異なる映像を同時に提示する構成。',
   'composition', array[]::text[], null, 'published', true),
  ('multi-panel-composition', 'Multi-Panel Composition', 'マルチパネル構成',
   'Multiple framed image panels are arranged as a coordinated graphic composition.',
   '複数の映像パネルを、相互に関係するグラフィックな構図として配置する表現。',
   'composition', array['multi screen'], null, 'published', true),
  ('dance-camera', 'Dance Camera', 'ダンスカメラ',
   'Camera movement, framing and distance are actively organized in relation to choreography and bodily rhythm.',
   '振付や身体のリズムとの関係に基づいて、カメラ移動・構図・距離を能動的に設計する映像言語。',
   'camera_language', array[]::text[], null, 'published', true),
  ('spatial-choreography', 'Spatial Choreography', '空間振付',
   'Performers, objects and camera are arranged through space as a coordinated movement system.',
   '演者、物体、カメラを空間内で連動する運動システムとして配置する表現。',
   'performance', array[]::text[], null, 'published', true),
  ('minimal-performance', 'Minimal Performance', 'ミニマル・パフォーマンス',
   'A performance-centered image reduced to a limited set, cast, palette or visual device.',
   'セット、出演者、色彩、視覚装置を限定し、パフォーマンスを中心に構成する表現。',
   'performance', array[]::text[], null, 'published', true),
  ('performance-film', 'Performance Film', 'パフォーマンスフィルム',
   'A work structured primarily around a performed action, dance or musical presence rather than plot progression.',
   '物語の進行よりも、演技、ダンス、音楽的な存在感を中心に構成する映像形式。',
   'performance', array[]::text[], null, 'published', true),
  ('stop-motion', 'Stop Motion', 'ストップモーション',
   'A visual language of deliberately incremental, frame-by-frame movement, regardless of the specific capture setup.',
   '特定の撮影装置に限らず、意図的に段階化されたコマ単位の動きを用いる映像言語。',
   'motion', array[]::text[], 'https://www.adobe.com/creativecloud/video/discover/stop-motion-animation.html', 'published', true),
  ('pixilation', 'Pixilation', 'ピクシレーション',
   'A stop-motion approach in which live performers are photographed frame by frame as animated subjects.',
   '実在の演者を一コマずつ撮影し、アニメーションの被写体として動かすストップモーション表現。',
   'motion', array['pixilation animation'], null, 'published', true),
  ('typography', 'Typography', 'タイポグラフィ',
   'Written language and letterform design function as a substantial visual element within the moving image.',
   '文字と言語の造形を、映像内の主要な視覚要素として用いる表現。',
   'composition', array[]::text[], null, 'published', true),
  ('kinetic-typography', 'Kinetic Typography', 'キネティックタイポグラフィ',
   'Typography whose movement, timing and transformation carry rhythm, emphasis or meaning.',
   '文字の移動、タイミング、変形によってリズム、強調、意味を伝える表現。',
   'motion', array['animated typography'], null, 'published', true),
  ('mixed-media', 'Mixed Media', 'ミクストメディア',
   'Two or more visibly distinct image-making media are combined as an intentional visual system.',
   '異なる二つ以上の映像・造形メディアを、意図的な視覚システムとして組み合わせる表現。',
   'image_treatment', array[]::text[], null, 'published', true),
  ('collage', 'Collage', 'コラージュ',
   'Disparate image fragments are juxtaposed, layered or assembled into a new composite field.',
   '異なる映像断片を並置・重層・再構成し、新しい複合画面を作る表現。',
   'image_treatment', array[]::text[], null, 'published', true),
  ('found-footage', 'Found Footage', 'ファウンドフッテージ',
   'Pre-existing recorded material is recontextualized as a primary part of a new work.',
   '既存の記録映像を、新しい作品の主要要素として再文脈化して用いる表現。',
   'image_treatment', array['archive footage'], null, 'published', true),
  ('pov', 'POV', 'POV',
   'A shot or sequence framed from the perceptual viewpoint of a character, participant or device.',
   '人物、参加者、装置の知覚的な視点から構図を作るショットまたはシークエンス。',
   'camera_language', array['point of view'], null, 'published', true),
  ('first-person', 'First Person', '一人称映像',
   'A broader visual narration sustained from the experiential position of an on-screen or implied subject.',
   '画面内または暗示された主体の体験的位置を継続して採用する、広義の一人称的映像構成。',
   'camera_language', array[]::text[], null, 'published', true),
  ('body-transformation', 'Body Transformation', '身体変容',
   'The visible alteration of a body is used as a central image, event or metaphor.',
   '身体の形態変化を、中心的なイメージ、出来事、比喩として用いる表現。',
   'image_treatment', array[]::text[], null, 'published', true),
  ('continuous-transformation', 'Continuous Transformation', '連続変容',
   'Subjects or environments change progressively while visual continuity is preserved.',
   '視覚的な連続性を保ちながら、被写体や環境が段階的に変化し続ける表現。',
   'motion', array[]::text[], null, 'published', true),
  ('optical-illusion', 'Optical Illusion', '錯視',
   'Framing, movement, scale or staging produces a deliberate mismatch between perceived and physical space.',
   '構図、運動、縮尺、舞台設計によって、知覚される空間と物理空間のずれを生む表現。',
   'composition', array[]::text[], null, 'published', true),
  ('forced-perspective', 'Forced Perspective', '強制遠近法',
   'Controlled viewpoint and scale relationships make subjects appear larger, smaller, nearer or farther than they are.',
   '視点と縮尺関係を制御し、被写体の大きさや距離を実際とは異なって見せる表現。',
   'composition', array[]::text[], null, 'published', true),
  ('infinite-zoom', 'Infinite Zoom', 'インフィニットズーム',
   'Successive changes of scale create an apparently unending movement into or out of nested imagery.',
   '入れ子状の映像を連続的に拡大・縮小し、終わりのない奥行き移動として見せる表現。',
   'motion', array['endless zoom'], null, 'published', true),
  ('graphic-composition', 'Graphic Composition', 'グラフィック構成',
   'Figures, shapes, color and negative space are arranged with a strongly graphic, design-led hierarchy.',
   '人物、形、色、余白を、グラフィックデザインを重視した強い階層で配置する表現。',
   'composition', array[]::text[], null, 'published', true),
  ('data-visualization', 'Data Visualization', 'データビジュアライゼーション',
   'Data values, structures or processes are translated into visible form as a central part of the work.',
   'データの値、構造、過程を視覚的な形へ変換し、作品の中心要素として用いる表現。',
   'composition', array[]::text[], null, 'published', true),
  ('surrealism', 'Surrealism', 'シュルレアリスム',
   'Dream logic, improbable juxtapositions or transformations disrupt ordinary spatial and causal expectations.',
   '夢の論理、非現実的な並置や変容によって、通常の空間・因果の期待を崩す表現。',
   'image_treatment', array['surreal'], null, 'published', true),
  ('interactive-video', 'Interactive Video', 'インタラクティブビデオ',
   'A moving-image work whose sequence, viewpoint or outcome can be affected by viewer input.',
   '視聴者の入力によって、映像の順序、視点、結果などが変化する作品形式。',
   'other', array[]::text[], null, 'published', true),
  ('long-form-narrative', 'Long-Form Narrative', '長編ナラティブ',
   'An extended music-video form in which dramatic scenes and narrative development exceed a conventional performance clip.',
   '通常の演奏・歌唱クリップを超え、ドラマ場面と物語展開を長い尺で構成するMV形式。',
   'narrative', array['music video short film'], null, 'published', true)
on conflict (slug) do update set
  name = excluded.name,
  name_ja = excluded.name_ja,
  description = excluded.description,
  description_ja = excluded.description_ja,
  visual_language_type = excluded.visual_language_type,
  aliases = excluded.aliases,
  definition_source_url = excluded.definition_source_url,
  lifecycle_status = excluded.lifecycle_status,
  is_active = excluded.is_active;

commit;
